name: "PSR Summary"
description: "NOT WORKING, cannot create a local file. Generates a markdown summary from the Python Semantic Release action, suitable for GitHub Actions workflow summaries."


inputs:
  psr-version:
    description: "Version output from the PSR action"
    required: false
  psr-released:
    description: "Released output from the PSR action"
    required: false
  changelog-file:
    description: "Path to the changelog file"
    required: false

runs:
  using: "composite"
  steps:

    - id: validate-inputs
      shell: bash
      run: |
        echo "Validating inputs..."
        echo "PSR Version: '${{ inputs.psr-version }}'"
        echo "PSR Released: '${{ inputs.psr-released }}'"
        echo "Changelog File: '${{ inputs.changelog-file }}'"
        echo "Input validation completed."
        echo ""

    - id: create-summary-file
      shell: bash
      run: |
        PSR_SUMMARY_FILE_PATH="/tmp/psr_summary.md"
        echo "Creating summary file at: $PSR_SUMMARY_FILE_PATH"
        echo "psr-summary-file-path=$PSR_SUMMARY_FILE_PATH" >> "$GITHUB_OUTPUT"

    - id: generate-summary
      shell: bash
      run: |
        
        {
          echo "## Python Semantic Release - GitHub Action"
          echo ""
          if [ -n "${{ inputs.psr-version }}" ]; then
            echo "Version: ${{ inputs.psr-version }}"
          else
            echo "Version: Not available"
          fi
          if [ -n "${{ inputs.psr-released }}" ]; then
            echo "Released: ${{ inputs.psr-released }}"
          else
            echo "Released: Not available"
          fi
          echo ""
          if [ -n "${{ inputs.changelog-file }}" ] && [ -f "${{ inputs.changelog-file }}" ]; then
            echo "-----"
            echo ""
            cat "${{ inputs.changelog-file }}"
          else
            echo "Changelog file not found or not provided."
          fi
        } > PSR_SUMMARY_FILE_PATH

        cat "$PSR_SUMMARY_FILE_PATH"

    - id: validate-summary
      shell: bash
      run: |
        echo "Validating the generated summary file at $PSR_SUMMARY_FILE_PATH..."
        ls -l "$PSR_SUMMARY_FILE_PATH"
        
        if [ -f "$PSR_SUMMARY_FILE_PATH" ]; then
          echo "Summary file created successfully at: $PSR_SUMMARY_FILE_PATH"
          head -n 10 "$PSR_SUMMARY_FILE_PATH"
        else
          echo "Error: Summary file was not created."
          exit 1
        fi


outputs:
    psr-summary-file-path:
      description: "Markdown summary"
      value: ${{ steps.generate-summary.outputs.psr-summary-file-path }}